# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.7
      - image: circleci/golang:1.8
      - image: circleci/golang:1.9
      - image: circleci/golang:1.10
      - image: circleci/golang:1.11
      - image: circleci/golang:1.12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/gopkg.in/webnice/lsf.v1/lsf
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: make test
